/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package farmacia;

import DataBase.Dao.DataBase;
import DataBase.Pojo.Trabajador;
import Modulos.Home;
import Permisos.Acceso;
import Registro.RegistrarPc;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class Login extends javax.swing.JFrame {
    private DataBase db;
    private Trabajador trabajador=null;
    public static final int REGISTRO=1;
    public static final int LOGIN=2;
    private int tipo;
    
    /**
     * Creates new form Login
     */
    public Login(int tipo) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.tipo=tipo;
        
        db=DataBase.createDateBase();
        if(db.testInternt("www.google.com")){
            if(!db.estaConectado() ){
                JOptionPane.showMessageDialog(this, "El sistema se encuentra desactivado.");
                this.dispose();
            }
        }else{
            JOptionPane.showMessageDialog(this, "No hay internet.");
            this.dispose();
        }
        if(tipo==LOGIN){
            this.msj.setText("");
            this.tema.setText("Login");
            
        }else{
            this.msj.setText("Permiso de un jefe");
            this.tema.setText("Registrar equipo");
        }
        enableCampos(true);
    }
    
    private void enableCampos(boolean boolen){
        usr.setEnabled(boolen);
        psw.setEnabled(boolen);
        btm.setEnabled(boolen);
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usr = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        psw = new javax.swing.JPasswordField();
        btm = new javax.swing.JButton();
        msj = new javax.swing.JLabel();
        tema = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/logo/usr1.png"))); // NOI18N

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Usuario");

        usr.setToolTipText("Ingresa el nombre de usuario.");
        usr.setEnabled(false);
        usr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usrActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Contraseña");

        psw.setEnabled(false);
        psw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pswActionPerformed(evt);
            }
        });

        btm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/boton/ok.png"))); // NOI18N
        btm.setText("Aceptar");
        btm.setEnabled(false);
        btm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmActionPerformed(evt);
            }
        });

        msj.setForeground(new java.awt.Color(204, 0, 0));
        msj.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        tema.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tema.setForeground(new java.awt.Color(0, 51, 102));
        tema.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(msj, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(psw))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(usr, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 42, Short.MAX_VALUE))
                    .addComponent(tema, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btm)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tema)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(3, 3, 3)
                .addComponent(msj, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(usr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(psw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btm, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void accion(){
        String pw="";
        for(int i=0;i<this.psw.getPassword().length;i++){
            pw+=psw.getPassword()[i];
        }
        
        
        enableCampos(false);
        switch(tipo){
            case REGISTRO:
                trabajador=db.getJefe(usr.getText().trim(), pw);
                if(trabajador!=null){
                    new RegistrarPc(this,trabajador).setVisible(true);
                    return;
                }
            break;
            case LOGIN:
                trabajador=db.getTrabajador(usr.getText().trim(), pw);
                
                if(trabajador!=null){
                    List permisos=db.getPermiso(usr.getText().trim(), pw);
                    
                    Acceso.setPermisos(permisos);
                    Acceso.ESTE_TRABAJADOR=trabajador;
                    Acceso.USUARIO=usr.getText();
                    if(Acceso.acceso(Acceso.LOGIN)){
                        this.dispose();
                        new Home(trabajador, permisos).setVisible(true);
                    }else{
                        JOptionPane.showMessageDialog(this, "No tiene permiso de acceso");
                        enableCampos(true);
                    }
                    return;
                }
                break;
        }
        JOptionPane.showMessageDialog(this, "Contraseña incorrecta");
        enableCampos(true);
    }
    private void btmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmActionPerformed
        accion();
    }//GEN-LAST:event_btmActionPerformed

    private void pswActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pswActionPerformed
        accion();
    }//GEN-LAST:event_pswActionPerformed

    private void usrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usrActionPerformed
        accion();
    }//GEN-LAST:event_usrActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btm;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel msj;
    private javax.swing.JPasswordField psw;
    private javax.swing.JLabel tema;
    private javax.swing.JTextField usr;
    // End of variables declaration//GEN-END:variables
}
