/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Modulos;

import DataBase.Dao.DataBase;
import EstructuraRow.RowConsulta;
import ModeloTabla.ModelT;
import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTable;
import static javax.swing.SwingConstants.RIGHT;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author Abina
 */
public class Caducado extends javax.swing.JDialog {
    private ModelT ModeloTablaAlmacen;
    private DataBase bd;
    /** private ModelT ModeloTablaAlmacen;
    private DataBase bd;
     * Creates new form Caducado
     */
    public Caducado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        bd=DataBase.createDateBase();
        crearTablaAlmacen();
        setLocationRelativeTo(parent);
    }
    
    private void bajaLote(int id){
        bd.bajaLotePorCaducidad(id);
    }
    
    private void crearTablaAlmacen(){
        Class classObejeto=java.lang.Object.class;
        Object titulo[]=new Object[]{"ID","Nombre","Precio","Ubicacion","Caducacion","Existencia"};
        Class tipoClases[]=new Class[6];
        for(int i=0;i<6;i++){
            tipoClases[i]=classObejeto;
        }
        
        ModeloTablaAlmacen=new ModelT(titulo,tipoClases);
        List<RowConsulta>  rr=new ArrayList<RowConsulta>();
        rr=bd.getCaducado();
        if(rr==null){
            rr=new ArrayList<RowConsulta>();
        }
        Integer size=rr.size();
        if(size==null)return;
        
        for(int i=0;i<size;i++){
            RowConsulta dato=rr.get(i);
            ModeloTablaAlmacen.addRow(new Object[]{});
            ModeloTablaAlmacen.setValueAt(dato.getLote().getId(), i, 0);
            ModeloTablaAlmacen.setValueAt(dato.getProducto().getNombre(), i, 1);
            ModeloTablaAlmacen.setValueAt(dato.getProducto().getPrecioVenta(), i, 2);
            ModeloTablaAlmacen.setValueAt(dato.getLote().getUbicacion(), i, 3);
            
            ModeloTablaAlmacen.setValueAt(dato.getLote().getCaducacion(), i, 4);
            ModeloTablaAlmacen.setValueAt((dato.getLote().getExistencia()>1000000000)?"+1G":dato.getLote().getExistencia(), i, 5);
            
        }
        tablaAlmacen.setDefaultRenderer(Object.class, new DefaultTableCellRenderer(){
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                Component component=super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column); 
                this.setHorizontalAlignment(RIGHT);
                
                if(row%2==0){
                    component.setBackground(Color.decode("#eaeaea"));
                }else{
                    component.setBackground(Color.WHITE);
                }
                if(isSelected){
                    component.setBackground(Color.decode("#0048ff"));
                }
                
                return component;
            }
            
            
        });
        tablaAlmacen.setModel(ModeloTablaAlmacen);
        tablaAlmacen.getColumnModel().getColumn(1).setMinWidth(100);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAlmacen = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Caducado");

        tablaAlmacen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaAlmacen);

        jButton2.setText("Eliminar seleccionados");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void eliminarPorRango(){
        int row[]=tablaAlmacen.getSelectedRows();
        for(int i=0;i<row.length;i++){
            try {
                int id=Integer.parseInt(ModeloTablaAlmacen.getValueAt(row[i], 0).toString());
                
                bd.bajaLotePorCaducidad(id);
            } catch (Exception e) {
                System.out.println(e);
            }
        }
        crearTablaAlmacen();
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        eliminarPorRango();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaAlmacen;
    // End of variables declaration//GEN-END:variables
}
