
package Modulos;

import Configuracion.Conf;
import DataBase.Dao.DataBase;
import DataBase.Pojo.Permiso;
import DataBase.Pojo.Trabajador;
import Permisos.Acceso;
import farmacia.Farmacia;
import java.awt.Color;
import java.awt.Desktop;
import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.io.InputStreamReader;
import static java.lang.Thread.sleep;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.text.DecimalFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


public class Home extends javax.swing.JFrame {
    private final float VERCION=0.1f;
    private Conf conf;
    private Trabajador trabajador;
    private List<Permiso> permisos;
    Cajero panelCAjero;
    PanelPackete panelPackete;
    Reporte PanelReporte;
    Configuracion configuracion;
    /**
     * Creates new form Home
     */
    public Home(Trabajador trabajador, List<Permiso> permisos) {
        initComponents();
        this.setTitle("PVB - V"+VERCION);
        this.trabajador=trabajador;
        this.permisos=permisos;
        
        this.setLocationRelativeTo(null);
        
        conf=Conf.getConf();
        
        panelCAjero=new Cajero(this,trabajador);
        panelPackete=new PanelPackete();
        PanelReporte=new Reporte(this);
        configuracion=new Configuracion(VERCION);
        panelCAjero.setSize(panel.getSize().width, panel.getSize().height);
        panelPackete.setSize(panel.getSize().width, panel.getSize().height);
        PanelReporte.setSize(panel.getSize().width, panel.getSize().height);
        configuracion.setSize(panel.getSize().width, panel.getSize().height);
        botonCajero();
        nombreCajero.setText("www.abinadi.com.mx");
        float f=10000000000.50f;
        DecimalFormat formato=new DecimalFormat("###,###.##");
        JFrame THIS=this;
        new Thread(){
            @Override
            public void run() {
                comprovarVercion();
                comprovarProductosVencido();
                
                //bocle infinito
                comprovarProductoAgotado();
            }
            
        }.start();

   //     numero.setText("$"+formato.format(f)+" MXN ");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        banner = new javax.swing.JPanel();
        nombreCajero = new javax.swing.JLabel();
        bannerBoton = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        botonPackete = new javax.swing.JButton();
        botonReporte = new javax.swing.JButton();
        botonReporte1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Punto de venta basico - Beta 1.0");
        setMinimumSize(new java.awt.Dimension(1280, 720));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                formComponentResized(evt);
            }
        });
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        panel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );

        banner.setBackground(new java.awt.Color(0, 0, 0));

        nombreCajero.setFont(new java.awt.Font("Dialog", 0, 30)); // NOI18N
        nombreCajero.setForeground(new java.awt.Color(255, 255, 255));
        nombreCajero.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nombreCajero.setText("name");

        bannerBoton.setBackground(new java.awt.Color(0, 0, 0));
        bannerBoton.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jButton1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/boton/sell1.png"))); // NOI18N
        jButton1.setMnemonic('1');
        jButton1.setText("  Cajero  ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        bannerBoton.add(jButton1);

        botonPackete.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        botonPackete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/boton/pack1.png"))); // NOI18N
        botonPackete.setMnemonic('2');
        botonPackete.setText("  Producto  ");
        botonPackete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPacketeActionPerformed(evt);
            }
        });
        bannerBoton.add(botonPackete);

        botonReporte.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        botonReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/boton/report1.png"))); // NOI18N
        botonReporte.setMnemonic('3');
        botonReporte.setText("  Reporte  ");
        botonReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReporteActionPerformed(evt);
            }
        });
        bannerBoton.add(botonReporte);

        botonReporte1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        botonReporte1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/boton/configuracion1.png"))); // NOI18N
        botonReporte1.setMnemonic('3');
        botonReporte1.setText("  Configuracion  ");
        botonReporte1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonReporte1ActionPerformed(evt);
            }
        });
        bannerBoton.add(botonReporte1);

        javax.swing.GroupLayout bannerLayout = new javax.swing.GroupLayout(banner);
        banner.setLayout(bannerLayout);
        bannerLayout.setHorizontalGroup(
            bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bannerLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(bannerBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(nombreCajero, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );
        bannerLayout.setVerticalGroup(
            bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bannerLayout.createSequentialGroup()
                .addGroup(bannerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nombreCajero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bannerBoton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(banner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(banner, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void comprovarProductoAgotado(){
        boolean activo=true;
        int esperaExtra=0;
        while(activo){
            try {

                List l=DataBase.createDateBase().getProductoAgotado();
                if(l!=null && l.size()>0){
                    if( JOptionPane.showConfirmDialog(this, "<HTML>Hay productos que se agotaros<br>¿Quieres ver la lista? <HTML/>", "", JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE)==0){

                        new ProductoAgotado(this, true).setVisible(true);
                    }else if(JOptionPane.showConfirmDialog(this, "<HTML> ¿Quieres que te recordemos más tarde <br>que hay productos agotados?<HTML/>", "", JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE)==1){
                        activo=false;
                        JOptionPane.showMessageDialog(this, "<html>No se te volverá a notificar <br>hasta que vuelva a iniciar el programa.</html>");
                    }else{
                        esperaExtra=60*60;
                    }
                    
                }
                Thread.sleep(1000*conf.getVerificarExistencia()+esperaExtra);
                esperaExtra=0;
            } catch (InterruptedException ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    private void comprovarVercion() {

        if(conf.isBuscarActualizacion()){
            try {
                URL url=new URL("http://abinadi.com.mx/UPDATE/pvb/vercion");
                BufferedReader br=new BufferedReader(new InputStreamReader(url.openStream()));
                float v=Float.parseFloat(br.readLine());
                if(v>VERCION){
                    if(JOptionPane.showConfirmDialog(this, "<HTML>Hay una nueva vercion<br>¿Quiere actualizar?</HTML>","",JOptionPane.YES_NO_OPTION)==0){
                        br.close();
                        Desktop.getDesktop().browse(new URI("http://www.abinadi.com.mx/blog/update-pvb/"));

                    }
                }      
            } catch (Exception ex) {
                Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
     private void comprovarProductosVencido(){
             
             
         
        try {
            sleep(1000*10);
            List c=DataBase.createDateBase().getCaducado();
            if(c!=null && c.size()>0){
                
                if(JOptionPane.showConfirmDialog(this, "<HTML>Hay productos que estan por caducar<br>¿Quiere ver la lista?<HTML/>", "Productos caducados",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE)==0){
                    new Caducado(this,true).setVisible(true);
                }   
            }

        } catch (InterruptedException ex) {
            Logger.getLogger(Home.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void botonCajero(){
        panel.removeAll();
        panel.add(panelCAjero);
        panel.revalidate();
        panel.repaint();
        banner.setBackground(Color.decode("#c0ffbc"));
        bannerBoton.setBackground(Color.decode("#c0ffbc"));
        nombreCajero.setForeground(Color.decode("#033300"));
    }
    private void botonConfiguracion(){
        panel.removeAll();
        panel.add(configuracion);
        panel.revalidate();
        panel.repaint();
        banner.setBackground(Color.decode("#d8d8d8"));
        bannerBoton.setBackground(Color.decode("#d8d8d8"));
        nombreCajero.setForeground(Color.decode("#595959"));
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        botonCajero();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentResized
        try {
            panelCAjero.setSize(panel.getSize().width, panel.getSize().height);
            panelPackete.setSize(panel.getSize().width, panel.getSize().height);
            PanelReporte.setSize(panel.getSize().width, panel.getSize().height);
            configuracion.setSize(panel.getSize().width, panel.getSize().height);
        } catch (Exception e) {
        }
        
    }//GEN-LAST:event_formComponentResized
 //              formWindowStateChanged
    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged

        try {
            panelCAjero.setSize(this.getSize().width-90, this.getSize().height-140);
            panelPackete.setSize(this.getSize().width-90, this.getSize().height-140);
            PanelReporte.setSize(this.getSize().width-90, this.getSize().height-140);
            configuracion.setSize(this.getSize().width-90, this.getSize().height-140);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_formWindowStateChanged
    private void botonPakete(){
        panel.removeAll();
        panel.add(panelPackete);
        panel.revalidate();
        panel.repaint();
        banner.setBackground(Color.decode("#ffe3c1"));
        bannerBoton.setBackground(Color.decode("#ffe3c1"));
        nombreCajero.setForeground(Color.decode("#8c4c00"));
    }
    private void botonPacketeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPacketeActionPerformed
        botonPakete();
    }//GEN-LAST:event_botonPacketeActionPerformed

    private void botonReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReporteActionPerformed
        panel.removeAll();
        panel.add(PanelReporte);
        panel.revalidate();
        panel.repaint();
        banner.setBackground(Color.decode("#f5ffbf"));
        bannerBoton.setBackground(Color.decode("#f5ffbf"));
        nombreCajero.setForeground(Color.decode("#cea500"));
        PanelReporte.refrescarDatos();
    }//GEN-LAST:event_botonReporteActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        Farmacia.getF().delete();
    }//GEN-LAST:event_formWindowClosing

    private void botonReporte1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReporte1ActionPerformed
        botonConfiguracion();
    }//GEN-LAST:event_botonReporte1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel banner;
    private javax.swing.JPanel bannerBoton;
    private javax.swing.JButton botonPackete;
    private javax.swing.JButton botonReporte;
    private javax.swing.JButton botonReporte1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel nombreCajero;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
