/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Modulos;

import Configuracion.Conf;
import DataBase.Dao.DataBase;
import DataBase.Pojo.Departamento;
import DataBase.Pojo.Lote;
import DataBase.Pojo.Producto;
import ModeloTabla.ModelT;
import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class PanelPackete extends javax.swing.JPanel {

    private ModelT modeloTabla;
    private DataBase bd;
    private List<Departamento> departamentos;
    private Conf conf;
    /**
     * Creates new form PanelPackete
     */
    public PanelPackete() {
        initComponents();
        bd=DataBase.createDateBase();
        conf=Conf.getConf();
        crearTabla();
        actualizarDepartamento();
    }
    private void actualizarDepartamento(){
        new Thread(){
            public void run(){
                try {
                    jComboBoxDepartamentos.removeAllItems();
                    departamentos=bd.getListAllDepartamento();
                    jComboBoxDepartamentos.addItem("");
                    for(Departamento d:departamentos){
                        jComboBoxDepartamentos.addItem(d.getNombre());
                    }    
                } catch (Exception e) {
                }
                
            }
        }.start();
    }
    private void crearTabla(){
        Class classObejeto=java.lang.Object.class;
        Object titulo[]=new Object[]{"Id","Codigo B","Nombre","Compra","Venta","Receta"};
        Class tipoClases[]=new Class[]{classObejeto,classObejeto,classObejeto,classObejeto,classObejeto,classObejeto};
        modeloTabla=new ModelT(titulo,tipoClases);
        List<Producto> productos=null;
        if(!nombreProductoBuscar.getText().isEmpty()){
            productos=bd.getProductoByNombre(nombreProductoBuscar.getText());
        }else{
            productos=new ArrayList<Producto>();
        }
        
        for(int i=0;i<productos.size();i++){
            Producto producto=productos.get(i);
            modeloTabla.addRow(new Object[]{});
            modeloTabla.setValueAt(producto.getId(), i, 0);
            modeloTabla.setValueAt(producto.getCodigoDeBarra(), i, 1);
            modeloTabla.setValueAt(producto.getNombre(), i, 2);
            modeloTabla.setValueAt(conf.moneda(producto.getPrecioCompra()), i, 3);
            modeloTabla.setValueAt(conf.moneda(producto.getPrecioVenta()), i, 4);
            modeloTabla.setValueAt((producto.isReceta())?"Si":"No", i, 5);
        }
        tabla.setDefaultRenderer(Object.class, new DefaultTableCellRenderer(){
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                Component component=super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column); 
                this.setHorizontalAlignment(RIGHT);
                
                if(row%2==0){
                    component.setBackground(Color.decode("#eaeaea"));
                }else{
                    component.setBackground(Color.WHITE);
                }
                if(isSelected){
                    component.setBackground(Color.decode("#0048ff"));
                }
                
                return component;
            }
            
            
        });
        tabla.setModel(modeloTabla);
        tabla.getColumnModel().getColumn(0).setWidth(30);
        tabla.getColumnModel().getColumn(2).setMinWidth(300);
        
    }

    Producto productoActualizar;
    private void actualizarCamposProducto(){
        mpcb.setText(productoActualizar.getCodigoDeBarra());
        mpn.setText(productoActualizar.getNombre());
        mppdc.setText(productoActualizar.getPrecioCompra()+"");
        mppv.setText(productoActualizar.getPrecioVenta()+"");
        mppm.setText(productoActualizar.getMinimo()+"");
        mpd.setText(productoActualizar.getDescripcion());
    }
    private void limpiarActualizacion(){
        productoActualizar=null;
        mpcb.setText("");
        mpn.setText("");
        mppdc.setText("");
        mppv.setText("");
        mppm.setText("");
        mpd.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        npcb = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        npn = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        nppdc = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        nppv = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        npa = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jComboBoxReceta = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        jComboBoxDepartamentos = new javax.swing.JComboBox<>();
        btnGuardarNuevoProducto = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        npd = new javax.swing.JTextArea();
        jLabel20 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        nppm = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        surtirCb = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        spn = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        spc = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btnGuardarSurtir = new javax.swing.JButton();
        spf = new javax.swing.JFormattedTextField();
        jButton4 = new javax.swing.JButton();
        spu = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        mpcb = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        mpn = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        mppdc = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        mppv = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        btnGuardarNuevoProducto1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        mpd = new javax.swing.JTextArea();
        jLabel29 = new javax.swing.JLabel();
        mppm = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        nombreProductoBuscar = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel12.setText("Nuevo producto");

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel13.setText("Codigo de barra");

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Nombre*");

        npn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                npnKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                npnKeyTyped(evt);
            }
        });

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel15.setText("Precio de compra*");

        nppdc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nppdcKeyTyped(evt);
            }
        });

        jLabel16.setText("Precio de venta");

        nppv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nppvKeyTyped(evt);
            }
        });

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Activo");

        npa.setVerifyInputWhenFocusTarget(false);

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Requiere receta");

        jComboBoxReceta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No", "Si" }));

        jLabel19.setText("Departamento*");

        btnGuardarNuevoProducto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/boton/save.png"))); // NOI18N
        btnGuardarNuevoProducto.setText("Guardar");
        btnGuardarNuevoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarNuevoProductoActionPerformed(evt);
            }
        });

        npd.setColumns(20);
        npd.setRows(5);
        jScrollPane3.setViewportView(npd);

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("Descripcion");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/boton/reload.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/boton/add.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        nppm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nppmKeyTyped(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setText("Producto Minimo");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnGuardarNuevoProducto)
                        .addGap(47, 47, 47))
                    .addComponent(jScrollPane3)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jComboBoxReceta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxDepartamentos, 0, 130, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3))
                            .addComponent(npn)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nppdc)
                                    .addComponent(npa))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nppv, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                    .addComponent(nppm)))
                            .addComponent(npcb))))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(npcb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(npn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(nppdc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(nppv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(npa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nppm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton3)
                    .addComponent(jButton1)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(jComboBoxReceta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel19)
                        .addComponent(jComboBoxDepartamentos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuardarNuevoProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("    Nuevo    ", jPanel6);

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel3.setText("Surtir producto");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Codigo Barra");

        surtirCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                surtirCbActionPerformed(evt);
            }
        });

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Nombre");

        spn.setEditable(false);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Cantidad*");

        spc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                spcKeyTyped(evt);
            }
        });

        jLabel6.setText("Caducidad (aaaa/mm/dd)*");

        btnGuardarSurtir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/boton/save.png"))); // NOI18N
        btnGuardarSurtir.setText("Guardar");
        btnGuardarSurtir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarSurtirActionPerformed(evt);
            }
        });

        try {
            spf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/boton/Search1.png"))); // NOI18N
        jButton4.setText("Buscar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel8.setText("Ubicacion*");

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/boton/powerFull.png"))); // NOI18N
        jButton5.setText("Max");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/boton/key.png"))); // NOI18N
        jButton6.setText("ID");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(spn)
                            .addComponent(spu)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(spc, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5)
                                .addGap(23, 23, 23)
                                .addComponent(jLabel6)
                                .addGap(24, 24, 24)
                                .addComponent(spf, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnGuardarSurtir))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(surtirCb)
                                .addGap(18, 18, 18)
                                .addComponent(jButton4)
                                .addGap(18, 18, 18)
                                .addComponent(jButton6)))))
                .addGap(24, 24, 24))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(surtirCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4)
                    .addComponent(jButton6))
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(spn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(spc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(spf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(spu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(btnGuardarSurtir, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(193, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("    Surtir    ", jPanel1);

        jLabel21.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel21.setText("Modificar producto");

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("Codigo de barra");

        mpcb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mpcbActionPerformed(evt);
            }
        });

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel23.setText("Nombre");

        mpn.setEditable(false);

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText("Precio de compra*");

        mppdc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mppdcKeyTyped(evt);
            }
        });

        jLabel25.setText("Precio de venta*");

        mppv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mppvKeyTyped(evt);
            }
        });

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel26.setText("Producto minimo*");

        btnGuardarNuevoProducto1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/boton/save.png"))); // NOI18N
        btnGuardarNuevoProducto1.setText("Guardar");
        btnGuardarNuevoProducto1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarNuevoProducto1ActionPerformed(evt);
            }
        });

        mpd.setColumns(20);
        mpd.setRows(5);
        jScrollPane4.setViewportView(mpd);

        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel29.setText("Descripcion");

        mppm.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                mppmKeyTyped(evt);
            }
        });

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/boton/key.png"))); // NOI18N
        jButton7.setText("ID");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/boton/Search1.png"))); // NOI18N
        jButton8.setText("Buscar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/boton/close.png"))); // NOI18N
        jButton9.setText("Cancelar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton9)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardarNuevoProducto1))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4)
                            .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(22, 22, 22)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(mpn)
                                    .addGroup(jPanel7Layout.createSequentialGroup()
                                        .addComponent(mppdc, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                                        .addComponent(jLabel25)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(mppv, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                        .addComponent(mpcb)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton8)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton7))
                                    .addComponent(mppm))))))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(mpcb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(mpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(mppdc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(mppv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(mppm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel29)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarNuevoProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("    Modificar    ", jPanel7);

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabla);

        jLabel11.setText("Nombre");

        nombreProductoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreProductoBuscarActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/boton/Search1.png"))); // NOI18N
        jButton2.setText("Buscar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nombreProductoBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(nombreProductoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel4.add(jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 1340, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
                .addGap(50, 50, 50))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        crearTabla();
    }//GEN-LAST:event_jButton2ActionPerformed
    private Producto producto;
    private void buscarPorCodigodeBarra(){
        try{
            producto=bd.getProductoByCodigoDeBarra(surtirCb.getText());
            
            
            if(producto==null)return;
            spn.setText(producto.getNombre());
            
        }catch(Exception e){
            
        }
    }
    
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        buscarPorCodigodeBarra();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnGuardarSurtirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarSurtirActionPerformed
        if(spc.getText().isEmpty() ||
                spf.getText().isEmpty() ||
                spn.getText().isEmpty() ||
                spu.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Los campos con (*) son obligatorios.");
            return;
        }
        
        Lote lote=new Lote();
        lote.setCaducacion(spf.getText());
        lote.setProductoId(producto.getId());
        
        try {
            if(Float.parseFloat(spc.getText())>1500000000){
                JOptionPane.showMessageDialog(this, "Es demaciado grande el lote","No se puede archivar",JOptionPane.WARNING_MESSAGE);
                return;
            }
            lote.setExistencia(Float.parseFloat(spc.getText()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "La cantidad tiene que ser un numero.");
            return;
        }
        lote.setUbicacion(spu.getText());
        if(bd.insert(lote)){
            JOptionPane.showMessageDialog(this, "Se a surtido correctamente");
            spc.setText("");
            spf.setText("");
            spu.setText("");
            spn.setText("");
            surtirCb.requestFocus();
        }else{
            JOptionPane.showMessageDialog(this, "Hay un error en la conexion.");
        }
        
    }//GEN-LAST:event_btnGuardarSurtirActionPerformed

    private void btnGuardarNuevoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarNuevoProductoActionPerformed
        
        if(npn.getText().isEmpty() ||
                nppdc.getText().isEmpty() ||
                nppv.getText().isEmpty() ||
                nppm.getText().isEmpty() ||
                jComboBoxDepartamentos.getSelectedItem().toString().equals("")){
            JOptionPane.showMessageDialog(this, "Los campos con (*) son obligatorios.");
            return;
        }
        Producto producto=new Producto();
        producto.setCodigoDeBarra((npcb.getText().trim().isEmpty())?null:npcb.getText());
        producto.setNombre(npn.getText().toLowerCase());
        
        try {
            producto.setPrecioCompra(Float.parseFloat(nppdc.getText()));
            producto.setPrecioVenta(Float.parseFloat(nppv.getText()));  
            producto.setMinimo(Float.parseFloat(nppm.getText()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "EL precio/producto minimo debe ser números reales.");
            return;
        }
        producto.setActivo(npa.getText());
        producto.setDescripcion(npd.getText());
        producto.setReceta(jComboBoxReceta.getSelectedIndex()==1);
        for(Departamento d:departamentos){
            if(d.getNombre().equals(jComboBoxDepartamentos.getSelectedItem().toString())){
                producto.setDepartamentoId(d.getId());
                break;
            }
        }
        if(bd.insert(producto)){
            JOptionPane.showMessageDialog(this, "Se guardo con exito");
            npn.setText("");
            nppdc.setText("");
            nppv.setText("");
            npd.setText("");
            npcb.setText("");
            npcb.requestFocus();
        }else{
            JOptionPane.showMessageDialog(this, "Algo salio mal con la conexion");
        }
        
        
    }//GEN-LAST:event_btnGuardarNuevoProductoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        actualizarDepartamento();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String nom=JOptionPane.showInputDialog("Añadir nombre del nuevo departamento");
        nom=nom.toLowerCase();
        if(nom==null || nom.isEmpty())return;
        Departamento departamento=new Departamento();
        departamento.setNombre(nom);
        if(bd.insert(departamento)){
            JOptionPane.showMessageDialog(this, "Se guardo correctamente");
        }else{
            JOptionPane.showMessageDialog(this, "Algo asilio mal con la conexion.");
        }
        actualizarDepartamento();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        spc.setText(1000000000+"");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void nombreProductoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreProductoBuscarActionPerformed
        crearTabla();
    }//GEN-LAST:event_nombreProductoBuscarActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try{
            String id=JOptionPane.showInputDialog(this,"ID");
            producto=bd.getProductoById(Integer.parseInt(id));
            if(producto==null)return;
            spn.setText(producto.getNombre());
            
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void surtirCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_surtirCbActionPerformed
        buscarPorCodigodeBarra();
    }//GEN-LAST:event_surtirCbActionPerformed

    private void btnGuardarNuevoProducto1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarNuevoProducto1ActionPerformed


        if(
                mppdc.getText().isEmpty() ||
                mppv.getText().isEmpty() ||
                mppm.getText().isEmpty() 
                ){
            JOptionPane.showMessageDialog(this, "Los campos con (*) son obligatorios.");
            return;
        }
        
        if(productoActualizar!=null){
            Producto ProductoNuevo=productoActualizar.clonar();
            ProductoNuevo.setPrecioCompra(Float.parseFloat(mppdc.getText()));
            ProductoNuevo.setPrecioVenta(Float.parseFloat(mppv.getText()));
            ProductoNuevo.setMinimo(Float.parseFloat(mppm.getText()));
            ProductoNuevo.setDescripcion(mpd.getText());
            if(bd.Update(productoActualizar,ProductoNuevo)){
                JOptionPane.showMessageDialog(this, "Producto actualizado");
                limpiarActualizacion();
            }else{
                JOptionPane.showMessageDialog(this, "Algo salio mal","Error",JOptionPane.ERROR_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_btnGuardarNuevoProducto1ActionPerformed

    private boolean isOneNumer(char c){
        return c=='.' || (c<='9' && c>='0');
    }
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        productoActualizar=null;
        if((productoActualizar=bd.getProductoCB(mpcb.getText()))!=null){
            actualizarCamposProducto();
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        limpiarActualizacion();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void mpcbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mpcbActionPerformed
        productoActualizar=null;
        if((productoActualizar=bd.getProductoCB(mpcb.getText()))!=null){
            actualizarCamposProducto();
        }
    }//GEN-LAST:event_mpcbActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        productoActualizar=null;
        if((productoActualizar=bd.getProductoCB(JOptionPane.showInputDialog("ID")))!=null){
            actualizarCamposProducto();
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void spcKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_spcKeyTyped
        char c=evt.getKeyChar();
        if(c>'9' || c<'0'){
            evt.consume();
        }
    }//GEN-LAST:event_spcKeyTyped

    private void nppdcKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nppdcKeyTyped
        if(!isOneNumer(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_nppdcKeyTyped

    private void nppvKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nppvKeyTyped
        if(!isOneNumer(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_nppvKeyTyped

    private void nppmKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nppmKeyTyped
        char c=evt.getKeyChar();
        if(c>'9' || c<'0'){
            evt.consume();
        }
    }//GEN-LAST:event_nppmKeyTyped

    private void mppdcKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mppdcKeyTyped
        if(!isOneNumer(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_mppdcKeyTyped

    private void mppvKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mppvKeyTyped
        if(!isOneNumer(evt.getKeyChar())){
            evt.consume();
        }
    }//GEN-LAST:event_mppvKeyTyped

    private void mppmKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mppmKeyTyped
        char c=evt.getKeyChar();
        if(c>'9' || c<'0'){
            evt.consume();
        }
    }//GEN-LAST:event_mppmKeyTyped

    private void npnKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_npnKeyTyped
        String c=evt.getKeyChar()+"";
        evt.setKeyChar(c.toUpperCase().charAt(0));
        
    }//GEN-LAST:event_npnKeyTyped

    private void npnKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_npnKeyReleased
        npn.setText(npn.getText().toUpperCase());
    }//GEN-LAST:event_npnKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardarNuevoProducto;
    private javax.swing.JButton btnGuardarNuevoProducto1;
    private javax.swing.JButton btnGuardarSurtir;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBoxDepartamentos;
    private javax.swing.JComboBox<String> jComboBoxReceta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField mpcb;
    private javax.swing.JTextArea mpd;
    private javax.swing.JTextField mpn;
    private javax.swing.JTextField mppdc;
    private javax.swing.JTextField mppm;
    private javax.swing.JTextField mppv;
    private javax.swing.JTextField nombreProductoBuscar;
    private javax.swing.JTextField npa;
    private javax.swing.JTextField npcb;
    private javax.swing.JTextArea npd;
    private javax.swing.JTextField npn;
    private javax.swing.JTextField nppdc;
    private javax.swing.JTextField nppm;
    private javax.swing.JTextField nppv;
    private javax.swing.JTextField spc;
    private javax.swing.JFormattedTextField spf;
    private javax.swing.JTextField spn;
    private javax.swing.JTextField spu;
    private javax.swing.JTextField surtirCb;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
