/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Modulos;

import DataBase.Dao.DataBase;
import EstructuraRow.RowConsulta;
import ModeloTabla.ModelT;
import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTable;
import static javax.swing.SwingConstants.RIGHT;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author Abina
 */
public class ProductoAgotado extends javax.swing.JDialog {
    private ModelT ModeloTablaAlmacen;
    private DataBase bd;
    /**
     * Creates new form ProductoAgotado
     */
    public ProductoAgotado(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
                bd=DataBase.createDateBase();
        crearTablaAlmacen();
        setLocationRelativeTo(parent);
    }

    private void crearTablaAlmacen(){
        Class classObejeto=java.lang.Object.class;
        Object titulo[]=new Object[]{"ID","CB","Nombre","Venta","Compra"};
        Class tipoClases[]=new Class[5];
        for(int i=0;i<5;i++){
            tipoClases[i]=classObejeto;
        }
        
        ModeloTablaAlmacen=new ModelT(titulo,tipoClases);
        List<RowConsulta>  rr=new ArrayList<RowConsulta>();
        rr=bd.getProductoAgotado();
        if(rr==null){
            rr=new ArrayList<RowConsulta>();
        }
        Integer size=rr.size();
        if(size==null)return;
        
        for(int i=0;i<size;i++){
            RowConsulta dato=rr.get(i);
            ModeloTablaAlmacen.addRow(new Object[]{});
            ModeloTablaAlmacen.setValueAt(dato.getProducto().getId(), i, 0);
            ModeloTablaAlmacen.setValueAt(dato.getProducto().getCodigoDeBarra(), i, 1);
            ModeloTablaAlmacen.setValueAt(dato.getProducto().getNombre(), i, 2);
            ModeloTablaAlmacen.setValueAt(dato.getProducto().getPrecioVenta(), i, 3);
            
            ModeloTablaAlmacen.setValueAt(dato.getProducto().getPrecioCompra(), i, 4);
            
        }
        tablaAlmacen.setDefaultRenderer(Object.class, new DefaultTableCellRenderer(){
            @Override
            public Component getTableCellRendererComponent(JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) {
                Component component=super.getTableCellRendererComponent(table, value, isSelected, hasFocus, row, column); 
                this.setHorizontalAlignment(RIGHT);
                
                if(row%2==0){
                    component.setBackground(Color.decode("#eaeaea"));
                }else{
                    component.setBackground(Color.WHITE);
                }
                if(isSelected){
                    component.setBackground(Color.decode("#0048ff"));
                }
                
                return component;
            }
            
            
        });
        tablaAlmacen.setModel(ModeloTablaAlmacen);
        tablaAlmacen.getColumnModel().getColumn(0).setMaxWidth(50);
        tablaAlmacen.getColumnModel().getColumn(2).setMinWidth(200);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAlmacen = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Productos Agotandos");

        tablaAlmacen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaAlmacen);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(190, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(50, 50, 50)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductoAgotado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductoAgotado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductoAgotado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductoAgotado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ProductoAgotado dialog = new ProductoAgotado(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaAlmacen;
    // End of variables declaration//GEN-END:variables
}
