/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Registro;

import DataBase.Dao.DataBase;
import DataBase.Pojo.Licencia;
import DataBase.Pojo.Trabajador;
import com.sun.java.swing.plaf.windows.WindowsLookAndFeel;
import farmacia.LicenciaConfig;
import farmacia.Login;
import java.io.FileWriter;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Sammy Guergachi <sguergachi at gmail.com>
 */
public class RegistrarPc extends javax.swing.JFrame {
    private DataBase db;
    private Trabajador jefe;
    /**
     * Creates new form RegistrarPc
     */
    public RegistrarPc(JFrame padre,Trabajador jefe) {
        initComponents();
        tipoDeEquipo.add(Pc);
        tipoDeEquipo.add(Cajero);
        this.setLocationRelativeTo(padre);
        db=DataBase.createDateBase();
        this.jefe=jefe;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipoDeEquipo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Cajero = new javax.swing.JRadioButton();
        Pc = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        panelNombreCajero = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nombreCajero = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Como se va usar este equipo.", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(102, 102, 102))); // NOI18N

        Cajero.setSelected(true);
        Cajero.setText("Cajero");
        Cajero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CajeroActionPerformed(evt);
            }
        });

        Pc.setText("Equipo administrativo");
        Pc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Pc)
                    .addComponent(Cajero))
                .addContainerGap(232, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Cajero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Pc)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        panelNombreCajero.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de la caja", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 0, 11), new java.awt.Color(102, 102, 102))); // NOI18N

        jLabel2.setText("Nombre");

        javax.swing.GroupLayout panelNombreCajeroLayout = new javax.swing.GroupLayout(panelNombreCajero);
        panelNombreCajero.setLayout(panelNombreCajeroLayout);
        panelNombreCajeroLayout.setHorizontalGroup(
            panelNombreCajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNombreCajeroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nombreCajero)
                .addContainerGap())
        );
        panelNombreCajeroLayout.setVerticalGroup(
            panelNombreCajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNombreCajeroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelNombreCajeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombreCajero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelNombreCajero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelNombreCajero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PcActionPerformed
        if(Pc.isSelected()){
            panelNombreCajero.setVisible(false);
        }
    }//GEN-LAST:event_PcActionPerformed

    private void CajeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CajeroActionPerformed
        if(Cajero.isSelected()){
            panelNombreCajero.setVisible(true);
        }
    }//GEN-LAST:event_CajeroActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        LicenciaConfig lc=new LicenciaConfig();
        try {
            Licencia licencia=new Licencia();
            licencia.setMac(LicenciaConfig.getMacAddres());
            licencia.setHostName(InetAddress.getLocalHost().getHostName());
            licencia.setLicencia(lc.crearlicencia());
            if(Cajero.isSelected()){
                licencia.setNombreCaja(nombreCajero.getText());
            }else{
                licencia.setNombreCaja(null);
            }
            if(db.altaPc(licencia,jefe)){
                String aux=JOptionPane.showInputDialog("Licencia");
                while(!aux.equalsIgnoreCase(licencia.getLicencia())){
                    JOptionPane.showMessageDialog(this, "numero de serie invalida.");
                    aux=JOptionPane.showInputDialog("Licencia");
                }
                FileWriter fw=new FileWriter("conf.bad");
                fw.write(lc.encrip(licencia.getLicencia()));
                fw.close();
                JOptionPane.showMessageDialog(this, "Listo");
                this.dispose();
                new Login(Login.LOGIN).setVisible(true);
                return;
            }
        } catch (Exception ex) {
            Logger.getLogger(RegistrarPc.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(this, "Operacion fallida.");
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Cajero;
    private javax.swing.JRadioButton Pc;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField nombreCajero;
    private javax.swing.JPanel panelNombreCajero;
    private javax.swing.ButtonGroup tipoDeEquipo;
    // End of variables declaration//GEN-END:variables
}
